### ISSUE TITLE
The app cannot run due to missing dependencies

### ISSUE THREAD

**Issue by dpancic** [pelagios/peripleo2#233]
Command sbt run returning following errors:

> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]  ::          UNRESOLVED DEPENDENCIES         ::
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]  :: com.atlassian.jwt#jwt-core;1.6.1: not found
> [warn]  :: com.atlassian.jwt#jwt-api;1.6.1: not found
> [warn]  :: org.geotools#gt-geojson;18.1: not found
> [warn]  ::::::::::::::::::::::::::::::::::::::::::::::
> [warn]
> [warn]  Note: Unresolved dependencies path:
> [warn]          com.atlassian.jwt:jwt-core:1.6.1
> [warn]            +- com.mohiva:play-silhouette_2.11:5.0.0 (/home/user/peripleo2/build.sbt#L18-71)
> [warn]            +- com.mohiva:play-silhouette-persistence_2.11:5.0.0 (/home/user/peripleo2/build.sbt#L18-71)
> [warn]            +- peripleo2:peripleo2_2.11:2.2
> [warn]          com.atlassian.jwt:jwt-api:1.6.1
> [warn]            +- com.mohiva:play-silhouette_2.11:5.0.0 (/home/user/peripleo2/build.sbt#L18-71)
> [warn]            +- com.mohiva:play-silhouette-persistence_2.11:5.0.0 (/home/user/peripleo2/build.sbt#L18-71)
> [warn]            +- peripleo2:peripleo2_2.11:2.2
> [warn]          org.geotools:gt-geojson:18.1 (/home/user/peripleo2/build.sbt#L18-71)
> [warn]            +- peripleo2:peripleo2_2.11:2.2
> [error] sbt.librarymanagement.ResolveException: unresolved dependency: com.atlassian.jwt#jwt-core;1.6.1: not found
> [error] unresolved dependency: com.atlassian.jwt#jwt-api;1.6.1: not found
> [error] unresolved dependency: org.geotools#gt-geojson;18.1: not found
> [error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
> [error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
> [error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
> [error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
> [error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
> [error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
> [error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
> [error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
> [error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
> [error]         at xsbt.boot.Using$.withResource(Using.scala:10)
> [error]         at xsbt.boot.Using$.apply(Using.scala:9)
> [error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
> [error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
> [error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
> [error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
> [error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
> [error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
> [error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
> [error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
> [error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
> [error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
> [error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
> [error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:38)
> [error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:91)
> [error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
> [error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:104)
> [error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
> [error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:104)
> [error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:87)
> [error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
> [error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:118)
> [error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2356)
> [error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
> [error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
> [error]         at sbt.std.Transform$$anon$4.work(System.scala:64)
> [error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
> [error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
> [error]         at sbt.Execute.work(Execute.scala:266)
> [error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
> [error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
> [error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
> [error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [error]         at java.lang.Thread.run(Thread.java:748)
> [error] (*:update) sbt.librarymanagement.ResolveException: unresolved dependency: com.atlassian.jwt#jwt-core;1.6.1: not found
> [error] unresolved dependency: com.atlassian.jwt#jwt-api;1.6.1: not found
> [error] unresolved dependency: org.geotools#gt-geojson;18.1: not found
> [error] Total time: 11 s, completed May 13, 2020 11:54:23 AM

**Comment by rsimon** [comment]
Hi, 

Peripleo is currently somewhat unsupported... But AFAIK some of the repositories for dependencies have moved in the meantime. Can you cross-compare with the build file in Recogito? I think adding the same resolvers as in this build file should fix the issue:

https://github.com/pelagios/recogito2/blob/1a9e43086805b46f59170483bb3f845c242d8baf/build.sbt#L20-L28

**Comment by dpancic** [comment]
Thank you @rsimon 

Adding resolvers from Recogito to build.sbt almost solved the problem.

There is one more missing dependency:

[error] (*:update) sbt.librarymanagement.ResolveException: download failed: com.lightbend.sbt#sbt-javaagent;0.1.4!sbt-javaagent.jar

**Comment by rsimon** [comment]
Hi,

ah - yes, I think we had the same problem in Recogito. Some repos went down in the meantime, others didn't get updated. In the end, the problem was with the version of the auth framework (Silhouette). I made a change to the build file which bumps the Silhouett version from 5.0.0 to 5.0.7 - which should be available in the current repos, along with all its transient dependencies. 

After that change, the build seemed to work again. Can `git pull` to the latest state from the master branch and try again?

**Comment by dpancic** [comment]
It works. Thank you
